services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=jpa"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=postgres"
    ports:
      - "5432:5432"
